"use strict";Object.defineProperty(exports, "__esModule", { value: true });exports.getDoctor = exports.getDoctors = void 0;var _db = require("../setup/db.js");function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {try {var info = gen[key](arg);var value = info.value;} catch (error) {reject(error);return;}if (info.done) {resolve(value);} else {Promise.resolve(value).then(_next, _throw);}}function _asyncToGenerator(fn) {return function () {var self = this,args = arguments;return new Promise(function (resolve, reject) {var gen = fn.apply(self, args);function _next(value) {asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);}function _throw(err) {asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);}_next(undefined);});};}

var getDoctors = /*#__PURE__*/function () {var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {var query;return regeneratorRuntime.wrap(function _callee$(_context) {while (1) {switch (_context.prev = _context.next) {case 0:
            query = "SELECT * FROM users WHERE role = 'doctor'";return _context.abrupt("return",
            (0, _db.doQueryParams)(query));case 2:case "end":return _context.stop();}}}, _callee);}));return function getDoctors() {return _ref.apply(this, arguments);};}();exports.getDoctors = getDoctors;


var getDoctor = /*#__PURE__*/function () {var _ref2 = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee2(id) {var query;return regeneratorRuntime.wrap(function _callee2$(_context2) {while (1) {switch (_context2.prev = _context2.next) {case 0:
            query = "SELECT * FROM doctors WHERE user_id = ?";return _context2.abrupt("return",
            (0, _db.doQueryParams)(query, [id]));case 2:case "end":return _context2.stop();}}}, _callee2);}));return function getDoctor(_x) {return _ref2.apply(this, arguments);};}();exports.getDoctor = getDoctor;